TemplateDotNetCore/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TemplateDotNetCore.Extensions;

namespace TemplateDotNetCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var email = User.GetSpecificClaim("Email");
            return View();
        }
    }
}

TemplateDotNetCore/Controllers/Components/BlogSlideViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TemplateDotNetCore.Controllers.Components
{
    public class BlogSlideViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

TemplateDotNetCore/Controllers/Components/DailyDealViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TemplateDotNetCore.Controllers.Components
{
    public class DailyDealViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

TemplateDotNetCore/Controllers/Components/ServiceViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TemplateDotNetCore.Controllers.Components
{
    public class ServiceViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

TemplateDotNetCore/Controllers/Components/SlideShowViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TemplateDotNetCore.Application.Interfaces;
using TemplateDotNetCore.Infrastucture.Enums;

namespace TemplateDotNetCore.Controllers.Components
{
    public class SlideShowViewComponent : ViewComponent
    {
        private ISlideService _slideService;

        public SlideShowViewComponent(ISlideService slideService)
        {
            _slideService = slideService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var slides = _slideService.GetAll();
            return View(slides);
        }
    }
}

TemplateDotNetCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TemplateDotNetCore.Models;

namespace TemplateDotNetCore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewData["BodyClass"] = "cms-index-index cms-home-page";
            return View();
        }

        [Route("thong-tin-ve-cong-ty.html")]
        public IActionResult About()
        {
            return View();
        }

        [Route("lien-he.html")]
        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

TemplateDotNetCore/Views/Home/About.cshtml
<!-- Breadcrumbs -->

<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <li class="home"> <a title="Go to Home Page" href="index.html">Home</a><span>&raquo;</span></li>
                    <li><strong>About Us</strong></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumbs End -->
<!-- Main Container -->

<div class="main container">

    <div class="about-page">
        <div class="col-xs-12 col-sm-6">

            <h1>Welcome to <span class="text_color">ShopMart</span></h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras lacus metus, convallis ut leo nec, tincidunt eleifend justo. Ut felis orci, hendrerit a pulvinar et, gravida ac lorem. Sed vitae molestie sapien, at sollicitudin tortor.<br>
                <br>
                Duis id volutpat libero, id vestibulum purus.Donec euismod accumsan felis, <a href="#">egestas lobortis velit tempor</a> vitae. Integer eget velit fermentum, dignissim odio non, bibendum velit.
            </p>
            <ul>
                <li><i class="fa fa-arrow-right"></i>&nbsp; <a href="#">Suspendisse potenti. Morbi mollis tellus ac sapien.</a></li>
                <li><i class="fa fa-arrow-right"></i>&nbsp; <a href="#">Cras id dui. Nam ipsum risus, rutrum vitae, vestibulum eu.</a></li>
                <li><i class="fa fa-arrow-right"></i>&nbsp; <a href="#">Phasellus accumsan cursus velit. Pellentesque egestas.</a></li>
                <li><i class="fa fa-arrow-right"></i>&nbsp; <a href="#">Lorem Ipsum generators on the Internet tend to repeat predefined.</a></li>
            </ul>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div class="single-img-add sidebar-add-slider">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active"> <img src="~/client-side/images/about_us_slide1.jpg" alt="slide1"> </div>
                        <div class="item"> <img src="~/client-side/images/about_us_slide2.jpg" alt="slide2"> </div>
                        <div class="item"> <img src="~/client-side/images/about_us_slide3.jpg" alt="slide3"> </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Section: services -->
<section id="service" class="text-center">



    <div class="container">

        <div class="row">
            <div class="col-sm-3 col-md-3">
                <div class="wow fadeInUp" data-wow-delay="0.2s">
                    <div class="service-box">
                        <div class="service-icon"> <i class="icon-diamond icons"></i> </div>
                        <div class="service-desc">
                            <h4>Web Design</h4>
                            <p>Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-md-3">
                <div class="wow fadeInLeft" data-wow-delay="0.2s">
                    <div class="service-box">
                        <div class="service-icon"> <i class="icon-settings icons"></i> </div>
                        <div class="service-desc">
                            <h4>Programming</h4>
                            <p>Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-md-3">
                <div class="wow fadeInUp" data-wow-delay="0.2s">
                    <div class="service-box">
                        <div class="service-icon"> <i class="icon-camera icons"></i> </div>
                        <div class="service-desc">
                            <h4>Photography</h4>
                            <p>Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 col-md-3">
                <div class="wow fadeInRight" data-wow-delay="0.2s">
                    <div class="service-box">
                        <div class="service-icon"> <i class="icon-magnifier-add icons"></i> </div>
                        <div class="service-desc">
                            <h4>SEO</h4>
                            <p>Lorem ipsum dolor sit amet set, consectetur utes anet adipisicing elit, sed do eiusmod tempor incidist.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Section: services -->
<div class="our-team">




    <div class="container">
        <div class="page-header">
            <h2>Our Team</h2>
        </div>
        <div class="row">
            <div class="col-xs-6 col-sm-3 col-md-3">
                <div class="wow bounceInUp" data-wow-delay="0.2s">
                    <div class="team">
                        <div class="inner">
                            <div class="avatar"><img src="~/client-side/images/team-img01.jpg" alt="HTML template" class="img-responsive" /></div>
                            <h5>Joana Doe</h5>
                            <p class="subtitle">Art-director</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 col-md-3">
                <div class="wow bounceInUp" data-wow-delay="0.5s">
                    <div class="team">
                        <div class="inner">
                            <div class="avatar"><img src="~/client-side/images/team-img02.jpg" alt="HTML template" class="img-responsive" /></div>
                            <h5>Josefine</h5>
                            <p class="subtitle">Team Leader</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 col-md-3">
                <div class="wow bounceInUp" data-wow-delay="0.8s">
                    <div class="team">
                        <div class="inner">
                            <div class="avatar"><img src="~/client-side/images/team-img03.jpg" alt="HTML template" class="img-responsive" /></div>
                            <h5>Paulo Moreira</h5>
                            <p class="subtitle">Senior Web Developer</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 col-md-3">
                <div class="wow bounceInUp" data-wow-delay="1s">
                    <div class="team">
                        <div class="inner">
                            <div class="avatar"><img src="~/client-side/images/team-img04.jpg" alt="HTML template" class="img-responsive" /></div>
                            <h5>Tom Joana</h5>
                            <p class="subtitle">Digital Creative Director</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@await Component.InvokeAsync("Service")

TemplateDotNetCore/Views/Home/Contact.cshtml
 <!-- Breadcrumbs -->

<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ul>
                    <li class="home"> <a title="Go to Home Page" href="index.html">Home</a><span>&raquo;</span></li>
                    <li><strong>Contact Us</strong></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumbs End -->
<!-- Main Container -->
<section class="main-container col1-layout">
    <div class="main container">
        <div class="row">
            <section class="col-main col-sm-12">
                <div id="contact" class="page-content page-contact">
                    <div class="page-title">
                        <h2>Contact Us</h2>
                    </div>
                    <div id="message-box-conact">We're available for new projects</div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6" id="contact_form_map">
                            <h3 class="page-subheading">Let's get in touch</h3>
                            <p>Lorem ipsum dolor sit amet onsectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor dapibus eget. Mauris tincidunt aliquam lectus sed vestibulum. Vestibulum bibendum suscipit mattis.</p>
                            <br />
                            <ul>
                                <li><i class="fa fa-circle"></i> Praesent nec tincidunt turpis.</li>
                                <li><i class="fa fa-circle"></i> Aliquam et nisi risus.&nbsp;Cras ut varius ante.</li>
                                <li><i class="fa fa-circle"></i> Ut congue gravida dolor, vitae viverra dolor.</li>
                            </ul>
                            <br />
                            <ul class="store_info">
                                <li><i class="fa fa-home"></i>7064 Lorem Ipsum Vestibulum 666/13</li>
                                <li><i class="fa fa-phone"></i><span>+ 012 315 678 1234</span></li>
                                <li><i class="fa fa-print"></i><span>+39 0035 356 765</span></li>
                                <li><i class="fa fa-envelope"></i>Email: <span><a href="mailto:support@justtheme.com">support@justthemevalley.com</a></span></li>
                            </ul>
                        </div>
                        <div class="col-sm-6">
                            <h3 class="page-subheading">Make an enquiry</h3>
                            <div class="contact-form-box">
                                <div class="form-selector">
                                    <label>Name</label>
                                    <input type="text" class="form-control input-sm" id="name" />
                                </div>
                                <div class="form-selector">
                                    <label>Email</label>
                                    <input type="text" class="form-control input-sm" id="email" />
                                </div>
                                <div class="form-selector">
                                    <label>Phone</label>
                                    <input type="text" class="form-control input-sm" id="phone" />
                                </div>
                                <div class="form-selector">
                                    <label>Message</label>
                                    <textarea class="form-control input-sm" rows="10" id="message"></textarea>
                                </div>
                                <div class="form-selector">
                                    <button class="button"><i class="icon-paper-plane icons"></i>&nbsp; <span>Send Message</span></button>
                                    &nbsp; <a href="#" class="button">Clear</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<!-- Main Container End -->
@await Component.InvokeAsync("Service")

TemplateDotNetCore/Views/Home/Index.cshtml
@section Scripts{
    <script src="~/client-app/controllers/home/index.js"></script>
    <script>
        var homeController = new HomeController();
        homeController.initialize();
    </script>
}
<!-- Slideshow  -->
@await Component.InvokeAsync("SlideShow")
<!-- service section -->
@await Component.InvokeAsync("Service")
@await Component.InvokeAsync("SpecialProductsOfferSliderBanner")
<!-- All products-->
@await Component.InvokeAsync("ProductSlideTab")
@await Component.InvokeAsync("DailyDeal")
@Html.Partial("_Banner.cshtml")
@await Component.InvokeAsync("FeatureProduct")
<!-- Blog -->
@await Component.InvokeAsync("BlogSlide")
<!-- our clients Slider -->

@await Component.InvokeAsync("BannerClientSlide")
<!-- BANNER-AREA-START -->
@await Component.InvokeAsync("BannerPromoteProduct")
<!-- BANNER-AREA-END -->
@await Component.InvokeAsync("FooterCustomersRateRegisterNewLetter")

TemplateDotNetCore/Views/Home/_Banner.cshtml
<div class="banner-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <figure> <a href="#" target="_self" class="image-wrapper"><img src="~/client-side/images/banner-laptop.jpg" alt="banner laptop"></a></figure>
            </div>
            <div class="col-sm-6">
                <figure> <a href="#" target="_self" class="image-wrapper"><img src="~/client-side/images/banner-mob.jpg" alt="banner moblie"></a></figure>
            </div>
        </div>
    </div>
</div>